-- Shared tables and durable single-authority handoff marker.
SET LOCAL search_path TO public;

CREATE TABLE image_cache (
    url TEXT PRIMARY KEY,
    bytes BYTEA NOT NULL,
    content_type TEXT NOT NULL,
    stored_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE source_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT COLLATE "C" NOT NULL,
    url TEXT NOT NULL,
    category TEXT NOT NULL,
    country TEXT NOT NULL,
    source_type TEXT NOT NULL,
    funding_type TEXT NOT NULL,
    bias_rating TEXT NOT NULL,
    ownership_label TEXT NOT NULL,
    factual_reporting TEXT NOT NULL,
    is_paywalled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT source_catalog_name_key UNIQUE (name)
);

CREATE TABLE thesis_schema_authority (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    schema_authority TEXT NOT NULL,
    alembic_handoff_revision TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO thesis_schema_authority (singleton, schema_authority, alembic_handoff_revision)
VALUES (TRUE, 'sqlx', '20260722_0006');
