-- Database schema and bootstrap data are owned by the explicit thesis-db SQLx migration runner.
-- The PostgreSQL image executes this file before application startup, so it intentionally performs no SQL.
-- Operators must run Database::migrate against this database before starting either application.
