from typing import Any, Sequence

def parse_feeds_parallel(
    sources_payload: Sequence[tuple[str, Sequence[str]]],
    max_workers: int,
) -> dict[str, Any]: ...
def extract_article_html(html: str) -> dict[str, Any]: ...
def extract_og_image_html(html: str) -> dict[str, Any]: ...
