import { Vector3 } from "three";
import { z } from "zod";
import type { CountryFeatureCollection } from "./interactive-globe-visuals-types";

const CountryFeatureSchema = z.object({
  geometry: z.object({ coordinates: z.unknown() }).nullable().optional(),
  properties: z
    .object({
      ADM0_A3: z.string().optional(),
      ISO_A2: z.string().optional(),
      NAME: z.string().optional(),
    })
    .catchall(z.unknown()),
});

const CountryCollectionSchema = z.object({ features: z.array(CountryFeatureSchema) });

const ATMOSPHERE_RADIUS_FACTOR = 1.03;

const BUMP_PLACEHOLDER_COLOR = [96, 96, 96, 255] as const;

const CAP_DEFAULT_COLOR = "rgba(255, 255, 255, 0.03)";

const CAP_SELECTED_COLOR = "rgba(233, 118, 43, 0.82)";

const CLOUD_PLACEHOLDER_COLOR = [0, 0, 0, 255] as const;

const CLOUD_RADIUS_FACTOR = 1.008;

const COLOR_PRECISION = 3;

const DEFAULT_PIXEL_RATIO = 1;

const DEFAULT_POLYGON_ALTITUDE = 0.006;

const DESKTOP_CLICK_ALTITUDE = 1.2;

const DESKTOP_DESELECT_ALTITUDE = 2;

const DESKTOP_FOCUS_ALTITUDE = 1.5;

const DESKTOP_LAT_OFFSET = -5;

const DESKTOP_OVERVIEW_ALTITUDE = 2.5;

const DPR_HIGH_CUTOFF = 2.25;

const DPR_MEDIUM_CUTOFF = 1.6;

const EARTH_RADIUS = 100;

const EMPTY_COUNTRY_COLLECTION = { features: [] } satisfies CountryFeatureCollection;

const EXTERNAL_ALTITUDE_BASE = 0.008;

const EXTERNAL_ALTITUDE_STEP = 0.016;

const EXTERNAL_CAP_ALPHA_BASE = 0.42;

const EXTERNAL_CAP_ALPHA_STEP = 0.24;

const EXTERNAL_CAP_BLUE_BASE = 162;

const EXTERNAL_CAP_BLUE_STEP = 58;

const EXTERNAL_CAP_GREEN_BASE = 132;

const EXTERNAL_CAP_GREEN_STEP = 48;

const EXTERNAL_CAP_RED_BASE = 102;

const EXTERNAL_CAP_RED_STEP = 42;

const EXTERNAL_HOVER_ALPHA_BASE = 0.72;

const EXTERNAL_HOVER_ALPHA_STEP = 0.16;

const EXTERNAL_HOVER_BLUE_BASE = 216;

const EXTERNAL_HOVER_BLUE_STEP = 24;

const EXTERNAL_HOVER_GREEN_BASE = 188;

const EXTERNAL_HOVER_GREEN_STEP = 28;

const EXTERNAL_HOVER_RED_BASE = 154;

const EXTERNAL_HOVER_RED_STEP = 28;

const EXTERNAL_SIDE_ALPHA_STEP = 0.14;

const EXTERNAL_SIDE_RGB = [122, 162, 190] as const;

const EXTERNAL_STROKE_ALPHA_STEP = 0.22;

const EXTERNAL_STROKE_RGB = [162, 196, 220] as const;

const FOCUS_TRANSITION_MS = 800;

const FULL_RATIO = 1;

const GLOBE_MIN_SIDE_HIGH = 900;

const GLOBE_MIN_SIDE_LOW = 560;

const GLOBE_TEXTURE_ROTATION_Y = -Math.PI / 2;

const HEAT_ALPHA_BASE = 0.54;

const HEAT_ALPHA_STEP = 0.28;

const HEAT_BLUE_BASE = 128;

const HEAT_BLUE_FLOOR = 34;

const HEAT_BLUE_STEP = 78;

const HEAT_GREEN_BASE = 192;

const HEAT_GREEN_STEP = 96;

const HEAT_RED_BASE = 214;

const HEAT_RED_STEP = 34;

const HIGHER_QUALITY_TIER = {
  anisotropyCap: 4,
  maxTextureSize: 2048,
  pixelRatioCap: 1.1,
  sphereSegments: 96,
  starCount: 1400,
};

const HOVER_ALPHA_BASE = 0.78;

const HOVER_ALPHA_STEP = 0.16;

const HOVER_ALTITUDE_BASE = 0.1;

const HOVER_ALTITUDE_STEP = 0.03;

const HOVER_BLUE_BASE = 176;

const HOVER_BLUE_FLOOR = 72;

const HOVER_BLUE_STEP = 88;

const HOVER_GREEN_BASE = 232;

const HOVER_GREEN_STEP = 48;

const HOVER_RED_BASE = 255;

const LABEL_BACKGROUND_RGB = "rgba(10, 10, 10, 0.92)";

const LABEL_BORDER_ALPHA = 0.12;

const LABEL_BORDER_WIDTH = 1;

const LABEL_BOX_SHADOW_OPACITY = 0.35;

const LABEL_BOX_SHADOW_SIZE = 40;

const LABEL_BOX_SHADOW_VERTICAL = 20;

const LABEL_DETAIL_SIZE = 12;

const LABEL_DETAIL_TEXT_COLOR = "rgba(234, 234, 234, 0.82)";

const LABEL_LETTER_SPACING = 0.16;

const LABEL_MARGIN_PAIR = 8;

const LABEL_MARGIN_SINGLE = 4;

const LABEL_META_SIZE = 10;

const LABEL_META_TEXT_COLOR = "rgba(234, 234, 234, 0.65)";

const LABEL_MIN_WIDTH = 180;

const LABEL_PADDING = 12;

const LABEL_TEXT_COLOR = "#EAEAEA";

const LABEL_TITLE_COLOR = "#e9762b";

const LABEL_TITLE_SIZE = 16;

const LOCAL_COUNTRY_GEOJSON_URL = "/globe/ne_110m_admin_0_countries.geojson";

const LOWER_QUALITY_TIER = {
  anisotropyCap: 2,
  maxTextureSize: 1024,
  pixelRatioCap: 0.9,
  sphereSegments: 52,
  starCount: 700,
};

const MIDDLE_QUALITY_TIER = {
  anisotropyCap: 3,
  maxTextureSize: 1536,
  pixelRatioCap: 1,
  sphereSegments: 72,
  starCount: 1000,
};

const MIN_TEXTURE_EDGE = 1;

const MOBILE_BREAKPOINT = 1024;

const MOBILE_CLICK_ALTITUDE = 2.25;

const MOBILE_FOCUS_ALTITUDE = 2.35;

const MOBILE_LAT_OFFSET = -18;

const MOBILE_OVERVIEW_ALTITUDE = 4.25;

const NIGHT_PLACEHOLDER_COLOR = [0, 0, 0, 255] as const;

const ANTLARCTICA_USER_ISO = "AQ";

const OPTIMIZED_TEXTURES = {
  bump: "/3dmodel/textures/optimized/earth-bump-2048.jpg",
  clouds: "/3dmodel/textures/optimized/clouds-earth-2048.webp",
  day: "/3dmodel/textures/optimized/earth-albedo-2048.jpg",
  night: "/3dmodel/textures/optimized/earth-night-lights-2048.png",
  surfaceMask: "/3dmodel/textures/optimized/earth-land-ocean-mask-2048.png",
} as const;

const PLACEHOLDER_DAY_COLOR = [5, 16, 34, 255] as const;

const PLACEHOLDER_TEXTURE_HEIGHT = 1;

const PLACEHOLDER_TEXTURE_WIDTH = 1;

const SELECTED_ALTITUDE_BASE = 0.055;

const SELECTED_ALTITUDE_STEP = 0.025;

const SIDE_ALPHA_BASE = 0.08;

const SIDE_DEFAULT_COLOR = "rgba(255, 255, 255, 0.028)";

const SIDE_HOVER_EXTERNAL_COLOR = "rgba(150, 196, 224, 0.5)";

const SIDE_HOVER_SOURCE_COLOR = "rgba(255, 214, 138, 0.58)";

const SIDE_SELECTED_COLOR = "rgba(233, 118, 43, 0.42)";

const SOURCE_ALTITUDE_BASE = 0.01;

const SOURCE_ALTITUDE_STEP = 0.024;

const SOURCE_SIDE_ALPHA_STEP = 0.16;

const SOURCE_SIDE_RGB = [214, 166, 90] as const;

const SOURCE_STROKE_ALPHA_STEP = 0.26;

const SOURCE_STROKE_RGB = [228, 190, 120] as const;

const STAR_FIELD_SPREAD_FACTOR = 34;

const STROKE_ALPHA_BASE = 0.16;

const STROKE_DEFAULT_COLOR = "rgba(255, 255, 255, 0.08)";

const STROKE_HOVER_EXTERNAL_COLOR = "rgba(198, 224, 242, 0.9)";

const STROKE_HOVER_SOURCE_COLOR = "rgba(255, 240, 204, 0.95)";

const STROKE_SELECTED_COLOR = "rgba(233, 118, 43, 0.85)";

const SUN_COMPONENT_X = -0.84;

const SUN_COMPONENT_Y = 0.42;

const SUN_COMPONENT_Z = 0.74;

const SUN_LIGHT_DIRECTION = new Vector3(
  SUN_COMPONENT_X,
  SUN_COMPONENT_Y,
  SUN_COMPONENT_Z,
).normalize();

const SUN_LIGHT_DISTANCE_FACTOR = 6;

const TRANSPARENT_RGBA = "rgba(0, 0, 0, 0)";

const UNKNOWN_ISO_LABEL = "--";

const ZERO_COUNT = 0;

const CLOUD_DRIFT_SPEED = 0.0032;

const LIGHTING_MODE_ALL_LIT = 0;

const LIGHTING_MODE_DAY_NIGHT = 1;

const MASK_PLACEHOLDER_COLOR = [0, 0, 0, 255] as const;

export {
  CountryFeatureSchema,
  CountryCollectionSchema,
  ATMOSPHERE_RADIUS_FACTOR,
  BUMP_PLACEHOLDER_COLOR,
  CAP_DEFAULT_COLOR,
  CAP_SELECTED_COLOR,
  CLOUD_PLACEHOLDER_COLOR,
  CLOUD_RADIUS_FACTOR,
  COLOR_PRECISION,
  DEFAULT_PIXEL_RATIO,
  DEFAULT_POLYGON_ALTITUDE,
  DESKTOP_CLICK_ALTITUDE,
  DESKTOP_DESELECT_ALTITUDE,
  DESKTOP_FOCUS_ALTITUDE,
  DESKTOP_LAT_OFFSET,
  DESKTOP_OVERVIEW_ALTITUDE,
  DPR_HIGH_CUTOFF,
  DPR_MEDIUM_CUTOFF,
  EARTH_RADIUS,
  EMPTY_COUNTRY_COLLECTION,
  EXTERNAL_ALTITUDE_BASE,
  EXTERNAL_ALTITUDE_STEP,
  EXTERNAL_CAP_ALPHA_BASE,
  EXTERNAL_CAP_ALPHA_STEP,
  EXTERNAL_CAP_BLUE_BASE,
  EXTERNAL_CAP_BLUE_STEP,
  EXTERNAL_CAP_GREEN_BASE,
  EXTERNAL_CAP_GREEN_STEP,
  EXTERNAL_CAP_RED_BASE,
  EXTERNAL_CAP_RED_STEP,
  EXTERNAL_HOVER_ALPHA_BASE,
  EXTERNAL_HOVER_ALPHA_STEP,
  EXTERNAL_HOVER_BLUE_BASE,
  EXTERNAL_HOVER_BLUE_STEP,
  EXTERNAL_HOVER_GREEN_BASE,
  EXTERNAL_HOVER_GREEN_STEP,
  EXTERNAL_HOVER_RED_BASE,
  EXTERNAL_HOVER_RED_STEP,
  EXTERNAL_SIDE_ALPHA_STEP,
  EXTERNAL_SIDE_RGB,
  EXTERNAL_STROKE_ALPHA_STEP,
  EXTERNAL_STROKE_RGB,
  FOCUS_TRANSITION_MS,
  FULL_RATIO,
  GLOBE_MIN_SIDE_HIGH,
  GLOBE_MIN_SIDE_LOW,
  GLOBE_TEXTURE_ROTATION_Y,
  HEAT_ALPHA_BASE,
  HEAT_ALPHA_STEP,
  HEAT_BLUE_BASE,
  HEAT_BLUE_FLOOR,
  HEAT_BLUE_STEP,
  HEAT_GREEN_BASE,
  HEAT_GREEN_STEP,
  HEAT_RED_BASE,
  HEAT_RED_STEP,
  HIGHER_QUALITY_TIER,
  HOVER_ALPHA_BASE,
  HOVER_ALPHA_STEP,
  HOVER_ALTITUDE_BASE,
  HOVER_ALTITUDE_STEP,
  HOVER_BLUE_BASE,
  HOVER_BLUE_FLOOR,
  HOVER_BLUE_STEP,
  HOVER_GREEN_BASE,
  HOVER_GREEN_STEP,
  HOVER_RED_BASE,
  LABEL_BACKGROUND_RGB,
  LABEL_BORDER_ALPHA,
  LABEL_BORDER_WIDTH,
  LABEL_BOX_SHADOW_OPACITY,
  LABEL_BOX_SHADOW_SIZE,
  LABEL_BOX_SHADOW_VERTICAL,
  LABEL_DETAIL_SIZE,
  LABEL_DETAIL_TEXT_COLOR,
  LABEL_LETTER_SPACING,
  LABEL_MARGIN_PAIR,
  LABEL_MARGIN_SINGLE,
  LABEL_META_SIZE,
  LABEL_META_TEXT_COLOR,
  LABEL_MIN_WIDTH,
  LABEL_PADDING,
  LABEL_TEXT_COLOR,
  LABEL_TITLE_COLOR,
  LABEL_TITLE_SIZE,
  LOCAL_COUNTRY_GEOJSON_URL,
  LOWER_QUALITY_TIER,
  MIDDLE_QUALITY_TIER,
  MIN_TEXTURE_EDGE,
  MOBILE_BREAKPOINT,
  MOBILE_CLICK_ALTITUDE,
  MOBILE_FOCUS_ALTITUDE,
  MOBILE_LAT_OFFSET,
  MOBILE_OVERVIEW_ALTITUDE,
  NIGHT_PLACEHOLDER_COLOR,
  ANTLARCTICA_USER_ISO,
  OPTIMIZED_TEXTURES,
  PLACEHOLDER_DAY_COLOR,
  PLACEHOLDER_TEXTURE_HEIGHT,
  PLACEHOLDER_TEXTURE_WIDTH,
  SELECTED_ALTITUDE_BASE,
  SELECTED_ALTITUDE_STEP,
  SIDE_ALPHA_BASE,
  SIDE_DEFAULT_COLOR,
  SIDE_HOVER_EXTERNAL_COLOR,
  SIDE_HOVER_SOURCE_COLOR,
  SIDE_SELECTED_COLOR,
  SOURCE_ALTITUDE_BASE,
  SOURCE_ALTITUDE_STEP,
  SOURCE_SIDE_ALPHA_STEP,
  SOURCE_SIDE_RGB,
  SOURCE_STROKE_ALPHA_STEP,
  SOURCE_STROKE_RGB,
  STAR_FIELD_SPREAD_FACTOR,
  STROKE_ALPHA_BASE,
  STROKE_DEFAULT_COLOR,
  STROKE_HOVER_EXTERNAL_COLOR,
  STROKE_HOVER_SOURCE_COLOR,
  STROKE_SELECTED_COLOR,
  SUN_LIGHT_DIRECTION,
  SUN_LIGHT_DISTANCE_FACTOR,
  TRANSPARENT_RGBA,
  UNKNOWN_ISO_LABEL,
  ZERO_COUNT,
  CLOUD_DRIFT_SPEED,
  LIGHTING_MODE_ALL_LIT,
  LIGHTING_MODE_DAY_NIGHT,
  MASK_PLACEHOLDER_COLOR,
};
